name: Test and Build

on:
  push:
    branches:
      - main
      - add-action

jobs:

  ghcr-image:
    name: Build and push GHCR image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        run: |
          docker build .  -t ghcr.io/pacoxu/slides-crawl:latest
          docker push ghcr.io/pacoxu/slides-crawl:latest



